name: Publish to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install @biomejs/cli-linux-x64 @rollup/rollup-linux-x64-gnu @esbuild/linux-x64
        
      - name: Run tests
        run: npm test
        
      - name: Run linter
        run: npm run lint
        
      - name: Build package
        run: npm run build
        
      - name: Configure package for GitHub Packages
        run: |
          echo "@razyone:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update package.json for GitHub Packages
        run: |
          npm pkg set name="@razyone/sub-agent-continue"
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"
          
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}